application: quicktodos
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: todo.application